// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Information about the principal, resource, and permission to check.
public struct AccessTuple: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The email address of the principal whose access you want to
  /// check. For example, `alice@example.com` or
  /// `my-service-account@my-project.iam.gserviceaccount.com`.
  ///
  /// The principal must be a Google Account or a service account. Other types of
  /// principals are not supported.
  public var principal: Swift.String = Swift.String()

  /// Required. The full resource name that identifies the resource. For example,
  /// `//compute.googleapis.com/projects/my-project/zones/us-central1-a/instances/my-instance`.
  ///
  /// For examples of full resource names for Google Cloud services, see
  /// https://cloud.google.com/iam/help/troubleshooter/full-resource-names.
  public var fullResourceName: Swift.String = Swift.String()

  /// Required. The IAM permission to check for, either in the `v1` permission
  /// format or the `v2` permission format.
  ///
  /// For a complete list of IAM permissions in the `v1` format, see
  /// https://cloud.google.com/iam/help/permissions/reference.
  ///
  /// For a list of IAM permissions in the `v2` format, see
  /// https://cloud.google.com/iam/help/deny/supported-permissions.
  ///
  /// For a complete list of predefined IAM roles and the permissions in each
  /// role, see https://cloud.google.com/iam/help/roles/reference.
  public var permission: Swift.String = Swift.String()

  /// Output only. The permission that Policy Troubleshooter checked for, in
  /// the `v2` format.
  public var permissionFqdn: Swift.String = Swift.String()

  /// Optional. Additional context for the request, such as the request time or
  /// IP address. This context allows Policy Troubleshooter to troubleshoot
  /// conditional role bindings and deny rules.
  public var conditionContext: ConditionContext? = nil

  /// Initialize a new instance of `AccessTuple`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessTuple().with { $0.principal = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.AccessTuple"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
