// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Whether IAM allow policies gives the principal the permission.
public enum AllowAccessState: Codable, Equatable, Sendable {
  /// Not specified.
  case unspecified
  /// The allow policy gives the principal the permission.
  case granted
  /// The allow policy doesn't give the principal the permission.
  case notGranted
  /// The allow policy gives the principal the permission if a condition
  /// expression evaluate to `true`. However, the sender of the request didn't
  /// provide enough context for Policy Troubleshooter to evaluate the condition
  /// expression.
  case unknownConditional
  /// The sender of the request doesn't have access to all of the allow policies
  /// that Policy Troubleshooter needs to evaluate the principal's access.
  case unknownInfo
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .granted: return 1
    case .notGranted: return 2
    case .unknownConditional: return 3
    case .unknownInfo: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "ALLOW_ACCESS_STATE_UNSPECIFIED"
    case .granted: return "ALLOW_ACCESS_STATE_GRANTED"
    case .notGranted: return "ALLOW_ACCESS_STATE_NOT_GRANTED"
    case .unknownConditional: return "ALLOW_ACCESS_STATE_UNKNOWN_CONDITIONAL"
    case .unknownInfo: return "ALLOW_ACCESS_STATE_UNKNOWN_INFO"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AllowAccessState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "ALLOW_ACCESS_STATE_UNSPECIFIED": self = .unspecified
    case "ALLOW_ACCESS_STATE_GRANTED": self = .granted
    case "ALLOW_ACCESS_STATE_NOT_GRANTED": self = .notGranted
    case "ALLOW_ACCESS_STATE_UNKNOWN_CONDITIONAL": self = .unknownConditional
    case "ALLOW_ACCESS_STATE_UNKNOWN_INFO": self = .unknownInfo
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AllowAccessState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .granted
    case 2: self = .notGranted
    case 3: self = .unknownConditional
    case 4: self = .unknownInfo
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .granted: return try container.encode(1)
    case .notGranted: return try container.encode(2)
    case .unknownConditional: return try container.encode(3)
    case .unknownInfo: return try container.encode(4)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
