// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details about how the relevant IAM allow policies affect the final access
/// state.
public struct AllowPolicyExplanation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Indicates whether the principal has the specified permission for the
  /// specified resource, based on evaluating all applicable IAM allow policies.
  public var allowAccessState: AllowAccessState = AllowAccessState()

  /// List of IAM allow policies that were evaluated to check the principal's
  /// permissions, with annotations to indicate how each policy contributed to
  /// the final result.
  ///
  /// The list of policies includes the policy for the resource itself, as well
  /// as allow policies that are inherited from higher levels of the resource
  /// hierarchy, including the organization, the folder, and the project.
  ///
  /// To learn more about the resource hierarchy, see
  /// https://cloud.google.com/iam/help/resource-hierarchy.
  public var explainedPolicies: [ExplainedAllowPolicy] = []

  /// The relevance of the allow policy type to the overall access state.
  public var relevance: HeuristicRelevance = HeuristicRelevance()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AllowPolicyExplanation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AllowPolicyExplanation().with { $0.allowAccessState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let allowAccessState = CodingKeys(stringValue: "allowAccessState")
    static let explainedPolicies = CodingKeys(stringValue: "explainedPolicies")
    static let relevance = CodingKeys(stringValue: "relevance")

    static let _knownKeys: Set<Swift.String> = [
      "allowAccessState",
      "explainedPolicies",
      "relevance",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(AllowAccessState.self, forKey: .allowAccessState) {
      self.allowAccessState = value
    }
    if let value = try container.decodeIfPresent(
      [ExplainedAllowPolicy].self, forKey: .explainedPolicies)
    {
      self.explainedPolicies = value
    }
    if let value = try container.decodeIfPresent(HeuristicRelevance.self, forKey: .relevance) {
      self.relevance = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.allowAccessState, forKey: .allowAccessState)
    try container.encode(self.explainedPolicies, forKey: .explainedPolicies)
    try container.encode(self.relevance, forKey: .relevance)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.AllowPolicyExplanation"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
