// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details about how a role binding in an allow policy affects a principal's
/// ability to use a permission.
public struct AllowBindingExplanation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Indicates whether _this role binding_ gives the specified
  /// permission to the specified principal on the specified resource.
  ///
  /// This field does _not_ indicate whether the principal actually has the
  /// permission on the resource. There might be another role binding that
  /// overrides this role binding. To determine whether the principal actually
  /// has the permission, use the `overall_access_state` field in the
  /// [TroubleshootIamPolicyResponse][google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse].
  ///
  /// [google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse]: <doc:TroubleshootIamPolicyResponse>
  public var allowAccessState: AllowAccessState = AllowAccessState()

  /// The role that this role binding grants. For example,
  /// `roles/compute.admin`.
  ///
  /// For a complete list of predefined IAM roles, as well as the permissions in
  /// each role, see https://cloud.google.com/iam/help/roles/reference.
  public var role: Swift.String = Swift.String()

  /// Indicates whether the role granted by this role binding contains the
  /// specified permission.
  public var rolePermission: RolePermissionInclusionState = RolePermissionInclusionState()

  /// The relevance of the permission's existence, or nonexistence, in the role
  /// to the overall determination for the entire policy.
  public var rolePermissionRelevance: HeuristicRelevance = HeuristicRelevance()

  /// The combined result of all memberships. Indicates if the principal is
  /// included in any role binding, either directly or indirectly.
  public var combinedMembership: AllowBindingExplanation.AnnotatedAllowMembership? = nil

  /// Indicates whether each role binding includes the principal specified in the
  /// request, either directly or indirectly. Each key identifies a principal in
  /// the role binding, and each value indicates whether the principal in the
  /// role binding includes the principal in the request.
  ///
  /// For example, suppose that a role binding includes the following principals:
  ///
  /// * `user:alice@example.com`
  /// * `group:product-eng@example.com`
  ///
  /// You want to troubleshoot access for `user:bob@example.com`. This user is a
  /// member of the group `group:product-eng@example.com`.
  ///
  /// For the first principal in the role binding, the key is
  /// `user:alice@example.com`, and the `membership` field in the value is set to
  /// `NOT_INCLUDED`.
  ///
  /// For the second principal in the role binding, the key is
  /// `group:product-eng@example.com`, and the `membership` field in the value is
  /// set to `INCLUDED`.
  public var memberships: [Swift.String: AllowBindingExplanation.AnnotatedAllowMembership] = [:]

  /// The relevance of this role binding to the overall determination for the
  /// entire policy.
  public var relevance: HeuristicRelevance = HeuristicRelevance()

  /// A condition expression that specifies when the role binding grants access.
  ///
  /// To learn about IAM Conditions, see
  /// https://cloud.google.com/iam/help/conditions/overview.
  public var condition: GoogleType.Expr? = nil

  /// Condition evaluation state for this role binding.
  public var conditionExplanation: ConditionExplanation? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AllowBindingExplanation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AllowBindingExplanation().with { $0.allowAccessState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let allowAccessState = CodingKeys(stringValue: "allowAccessState")
    static let role = CodingKeys(stringValue: "role")
    static let rolePermission = CodingKeys(stringValue: "rolePermission")
    static let rolePermissionRelevance = CodingKeys(stringValue: "rolePermissionRelevance")
    static let combinedMembership = CodingKeys(stringValue: "combinedMembership")
    static let memberships = CodingKeys(stringValue: "memberships")
    static let relevance = CodingKeys(stringValue: "relevance")
    static let condition = CodingKeys(stringValue: "condition")
    static let conditionExplanation = CodingKeys(stringValue: "conditionExplanation")

    static let _knownKeys: Set<Swift.String> = [
      "allowAccessState",
      "role",
      "rolePermission",
      "rolePermissionRelevance",
      "combinedMembership",
      "memberships",
      "relevance",
      "condition",
      "conditionExplanation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(AllowAccessState.self, forKey: .allowAccessState) {
      self.allowAccessState = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .role) {
      self.role = value
    }
    if let value = try container.decodeIfPresent(
      RolePermissionInclusionState.self, forKey: .rolePermission)
    {
      self.rolePermission = value
    }
    if let value = try container.decodeIfPresent(
      HeuristicRelevance.self, forKey: .rolePermissionRelevance)
    {
      self.rolePermissionRelevance = value
    }
    self.combinedMembership = try container.decodeIfPresent(
      AllowBindingExplanation.AnnotatedAllowMembership.self, forKey: .combinedMembership)
    if let value = try container.decodeIfPresent(
      [Swift.String: AllowBindingExplanation.AnnotatedAllowMembership].self, forKey: .memberships)
    {
      self.memberships = value
    }
    if let value = try container.decodeIfPresent(HeuristicRelevance.self, forKey: .relevance) {
      self.relevance = value
    }
    self.condition = try container.decodeIfPresent(GoogleType.Expr.self, forKey: .condition)
    self.conditionExplanation = try container.decodeIfPresent(
      ConditionExplanation.self, forKey: .conditionExplanation)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.allowAccessState, forKey: .allowAccessState)
    try container.encode(self.role, forKey: .role)
    try container.encode(self.rolePermission, forKey: .rolePermission)
    try container.encode(self.rolePermissionRelevance, forKey: .rolePermissionRelevance)
    try container.encodeIfPresent(self.combinedMembership, forKey: .combinedMembership)
    try container.encode(self.memberships, forKey: .memberships)
    try container.encode(self.relevance, forKey: .relevance)
    try container.encodeIfPresent(self.condition, forKey: .condition)
    try container.encodeIfPresent(self.conditionExplanation, forKey: .conditionExplanation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Details about whether the role binding includes the principal.
  public struct AnnotatedAllowMembership: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Indicates whether the role binding includes the principal.
    public var membership: MembershipMatchingState = MembershipMatchingState()

    /// The relevance of the principal's status to the overall determination for
    /// the role binding.
    public var relevance: HeuristicRelevance = HeuristicRelevance()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AnnotatedAllowMembership`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnnotatedAllowMembership().with { $0.membership = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let membership = CodingKeys(stringValue: "membership")
      static let relevance = CodingKeys(stringValue: "relevance")

      static let _knownKeys: Set<Swift.String> = [
        "membership",
        "relevance",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        MembershipMatchingState.self, forKey: .membership)
      {
        self.membership = value
      }
      if let value = try container.decodeIfPresent(HeuristicRelevance.self, forKey: .relevance) {
        self.relevance = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.membership, forKey: .membership)
      try container.encode(self.relevance, forKey: .relevance)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.AllowBindingExplanation.AnnotatedAllowMembership"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.AllowBindingExplanation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
