// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Details about how a role binding in an allow policy affects a principal's
/// ability to use a permission.
public struct AllowBindingExplanation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Indicates whether _this role binding_ gives the specified
  /// permission to the specified principal on the specified resource.
  ///
  /// This field does _not_ indicate whether the principal actually has the
  /// permission on the resource. There might be another role binding that
  /// overrides this role binding. To determine whether the principal actually
  /// has the permission, use the `overall_access_state` field in the
  /// [TroubleshootIamPolicyResponse][google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse].
  ///
  /// [google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse]: <doc:TroubleshootIamPolicyResponse>
  public var allowAccessState: AllowAccessState = AllowAccessState()

  /// The role that this role binding grants. For example,
  /// `roles/compute.admin`.
  ///
  /// For a complete list of predefined IAM roles, as well as the permissions in
  /// each role, see https://cloud.google.com/iam/help/roles/reference.
  public var role: Swift.String = Swift.String()

  /// Indicates whether the role granted by this role binding contains the
  /// specified permission.
  public var rolePermission: RolePermissionInclusionState = RolePermissionInclusionState()

  /// The relevance of the permission's existence, or nonexistence, in the role
  /// to the overall determination for the entire policy.
  public var rolePermissionRelevance: HeuristicRelevance = HeuristicRelevance()

  /// The combined result of all memberships. Indicates if the principal is
  /// included in any role binding, either directly or indirectly.
  public var combinedMembership: AllowBindingExplanation.AnnotatedAllowMembership? = nil

  /// Indicates whether each role binding includes the principal specified in the
  /// request, either directly or indirectly. Each key identifies a principal in
  /// the role binding, and each value indicates whether the principal in the
  /// role binding includes the principal in the request.
  ///
  /// For example, suppose that a role binding includes the following principals:
  ///
  /// * `user:alice@example.com`
  /// * `group:product-eng@example.com`
  ///
  /// You want to troubleshoot access for `user:bob@example.com`. This user is a
  /// member of the group `group:product-eng@example.com`.
  ///
  /// For the first principal in the role binding, the key is
  /// `user:alice@example.com`, and the `membership` field in the value is set to
  /// `NOT_INCLUDED`.
  ///
  /// For the second principal in the role binding, the key is
  /// `group:product-eng@example.com`, and the `membership` field in the value is
  /// set to `INCLUDED`.
  public var memberships: [Swift.String: AllowBindingExplanation.AnnotatedAllowMembership] = [:]

  /// The relevance of this role binding to the overall determination for the
  /// entire policy.
  public var relevance: HeuristicRelevance = HeuristicRelevance()

  /// A condition expression that specifies when the role binding grants access.
  ///
  /// To learn about IAM Conditions, see
  /// https://cloud.google.com/iam/help/conditions/overview.
  public var condition: GoogleType.Expr? = nil

  /// Condition evaluation state for this role binding.
  public var conditionExplanation: ConditionExplanation? = nil

  /// Initialize a new instance of `AllowBindingExplanation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AllowBindingExplanation().with { $0.allowAccessState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Details about whether the role binding includes the principal.
  public struct AnnotatedAllowMembership: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Indicates whether the role binding includes the principal.
    public var membership: MembershipMatchingState = MembershipMatchingState()

    /// The relevance of the principal's status to the overall determination for
    /// the role binding.
    public var relevance: HeuristicRelevance = HeuristicRelevance()

    /// Initialize a new instance of `AnnotatedAllowMembership`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnnotatedAllowMembership().with { $0.membership = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.AllowBindingExplanation.AnnotatedAllowMembership"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.AllowBindingExplanation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
