// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Additional context for troubleshooting conditional role bindings and deny
/// rules.
public struct ConditionContext: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Represents a target resource that is involved with a network activity.
  /// If multiple resources are involved with an activity, this must be the
  /// primary one.
  public var resource: ConditionContext.Resource? = nil

  /// The destination of a network activity, such as accepting a TCP connection.
  /// In a multi-hop network activity, the destination represents the receiver of
  /// the last hop.
  public var destination: ConditionContext.Peer? = nil

  /// Represents a network request, such as an HTTP request.
  public var request: ConditionContext.Request? = nil

  /// Output only. The effective tags on the resource. The effective tags are
  /// fetched during troubleshooting.
  public var effectiveTags: [ConditionContext.EffectiveTag] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConditionContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConditionContext().with { $0.resource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let resource = CodingKeys(stringValue: "resource")
    static let destination = CodingKeys(stringValue: "destination")
    static let request = CodingKeys(stringValue: "request")
    static let effectiveTags = CodingKeys(stringValue: "effectiveTags")

    static let _knownKeys: Set<Swift.String> = [
      "resource",
      "destination",
      "request",
      "effectiveTags",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.resource = try container.decodeIfPresent(ConditionContext.Resource.self, forKey: .resource)
    self.destination = try container.decodeIfPresent(
      ConditionContext.Peer.self, forKey: .destination)
    self.request = try container.decodeIfPresent(ConditionContext.Request.self, forKey: .request)
    if let value = try container.decodeIfPresent(
      [ConditionContext.EffectiveTag].self, forKey: .effectiveTags)
    {
      self.effectiveTags = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.resource, forKey: .resource)
    try container.encodeIfPresent(self.destination, forKey: .destination)
    try container.encodeIfPresent(self.request, forKey: .request)
    try container.encode(self.effectiveTags, forKey: .effectiveTags)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Core attributes for a resource. A resource is an
  /// addressable (named) entity provided by the destination service. For
  /// example, a Compute Engine instance.
  public struct Resource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The name of the service that this resource belongs to, such as
    /// `compute.googleapis.com`. The service name might not match the DNS
    /// hostname that actually serves the request.
    ///
    /// For a full list of resource service values, see
    /// https://cloud.google.com/iam/help/conditions/resource-services
    public var service: Swift.String = Swift.String()

    /// The stable identifier (name) of a resource on the `service`. A resource
    /// can be logically identified as `//{resource.service}/{resource.name}`.
    /// Unlike the resource URI, the resource name doesn't contain any protocol
    /// and version information.
    ///
    /// For a list of full resource name formats, see
    /// https://cloud.google.com/iam/help/troubleshooter/full-resource-names
    public var name: Swift.String = Swift.String()

    /// The type of the resource, in the format `{service}/{kind}`.
    ///
    /// For a full list of resource type values, see
    /// https://cloud.google.com/iam/help/conditions/resource-types
    public var type: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Resource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Resource().with { $0.service = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let service = CodingKeys(stringValue: "service")
      static let name = CodingKeys(stringValue: "name")
      static let type = CodingKeys(stringValue: "type")

      static let _knownKeys: Set<Swift.String> = [
        "service",
        "name",
        "type",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .service) {
        self.service = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.service, forKey: .service)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.type, forKey: .type)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.ConditionContext.Resource"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// This message defines attributes for a node that handles a network request.
  /// The node can be either a service or an application that sends, forwards,
  /// or receives the request. Service peers should fill in
  /// `principal` and `labels` as appropriate.
  public struct Peer: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The IPv4 or IPv6 address of the peer.
    public var ip: Swift.String = Swift.String()

    /// The network port of the peer.
    public var port: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Peer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Peer().with { $0.ip = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ip = CodingKeys(stringValue: "ip")
      static let port = CodingKeys(stringValue: "port")

      static let _knownKeys: Set<Swift.String> = [
        "ip",
        "port",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ip) {
        self.ip = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .port) {
        self.port = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.ip, forKey: .ip)
      try container.encode(self.port, forKey: .port)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.ConditionContext.Peer"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// This message defines attributes for an HTTP request. If the actual
  /// request is not an HTTP request, the runtime system should try to map
  /// the actual request to an equivalent HTTP request.
  public struct Request: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The timestamp when the destination service receives the first
    /// byte of the request.
    public var receiveTime: GoogleWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Request`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Request().with { $0.receiveTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let receiveTime = CodingKeys(stringValue: "receiveTime")

      static let _knownKeys: Set<Swift.String> = [
        "receiveTime"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.receiveTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .receiveTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.receiveTime, forKey: .receiveTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.ConditionContext.Request"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A tag that applies to a resource during policy evaluation. Tags can be
  /// either directly bound to a resource or inherited from its ancestor.
  /// `EffectiveTag` contains the `name` and `namespaced_name` of the tag value
  /// and tag key, with additional fields of `inherited` to indicate the
  /// inheritance status of the effective tag.
  public struct EffectiveTag: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Resource name for TagValue in the format `tagValues/456`.
    public var tagValue: Swift.String = Swift.String()

    /// Output only. The namespaced name of the TagValue. Can be in the form
    /// `{organization_id}/{tag_key_short_name}/{tag_value_short_name}` or
    /// `{project_id}/{tag_key_short_name}/{tag_value_short_name}` or
    /// `{project_number}/{tag_key_short_name}/{tag_value_short_name}`.
    public var namespacedTagValue: Swift.String = Swift.String()

    /// Output only. The name of the TagKey, in the format `tagKeys/{id}`, such
    /// as `tagKeys/123`.
    public var tagKey: Swift.String = Swift.String()

    /// Output only. The namespaced name of the TagKey. Can be in the form
    /// `{organization_id}/{tag_key_short_name}` or
    /// `{project_id}/{tag_key_short_name}` or
    /// `{project_number}/{tag_key_short_name}`.
    public var namespacedTagKey: Swift.String = Swift.String()

    /// The parent name of the tag key.
    /// Must be in the format `organizations/{organization_id}` or
    /// `projects/{project_number}`
    public var tagKeyParentName: Swift.String = Swift.String()

    /// Output only. Indicates the inheritance status of a tag value
    /// attached to the given resource. If the tag value is inherited from one of
    /// the resource's ancestors, inherited will be true. If false, then the tag
    /// value is directly attached to the resource, inherited will be false.
    public var inherited: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EffectiveTag`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EffectiveTag().with { $0.tagValue = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let tagValue = CodingKeys(stringValue: "tagValue")
      static let namespacedTagValue = CodingKeys(stringValue: "namespacedTagValue")
      static let tagKey = CodingKeys(stringValue: "tagKey")
      static let namespacedTagKey = CodingKeys(stringValue: "namespacedTagKey")
      static let tagKeyParentName = CodingKeys(stringValue: "tagKeyParentName")
      static let inherited = CodingKeys(stringValue: "inherited")

      static let _knownKeys: Set<Swift.String> = [
        "tagValue",
        "namespacedTagValue",
        "tagKey",
        "namespacedTagKey",
        "tagKeyParentName",
        "inherited",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tagValue) {
        self.tagValue = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .namespacedTagValue) {
        self.namespacedTagValue = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tagKey) {
        self.tagKey = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .namespacedTagKey) {
        self.namespacedTagKey = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tagKeyParentName) {
        self.tagKeyParentName = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .inherited) {
        self.inherited = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.tagValue, forKey: .tagValue)
      try container.encode(self.namespacedTagValue, forKey: .namespacedTagValue)
      try container.encode(self.tagKey, forKey: .tagKey)
      try container.encode(self.namespacedTagKey, forKey: .namespacedTagKey)
      try container.encode(self.tagKeyParentName, forKey: .tagKeyParentName)
      try container.encode(self.inherited, forKey: .inherited)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.ConditionContext.EffectiveTag"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.ConditionContext"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
