// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// Details about how a deny rule in a deny policy affects a principal's ability
/// to use a permission.
public struct DenyRuleExplanation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Indicates whether _this rule_ denies the specified permission to
  /// the specified principal for the specified resource.
  ///
  /// This field does _not_ indicate whether the principal is actually denied on
  /// the permission for the resource. There might be another rule that overrides
  /// this rule. To determine whether the principal actually has the permission,
  /// use the `overall_access_state` field in the
  /// [TroubleshootIamPolicyResponse][google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse].
  ///
  /// [google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse]: <doc:TroubleshootIamPolicyResponse>
  public var denyAccessState: DenyAccessState = DenyAccessState()

  /// Indicates whether the permission in the request is listed as a denied
  /// permission in the deny rule.
  public var combinedDeniedPermission: DenyRuleExplanation.AnnotatedPermissionMatching? = nil

  /// Lists all denied permissions in the deny rule and indicates whether each
  /// permission matches the permission in the request.
  ///
  /// Each key identifies a denied permission in the rule, and each value
  /// indicates whether the denied permission matches the permission in the
  /// request.
  public var deniedPermissions: [Swift.String: DenyRuleExplanation.AnnotatedPermissionMatching] =
    [:]

  /// Indicates whether the permission in the request is listed as an exception
  /// permission in the deny rule.
  public var combinedExceptionPermission: DenyRuleExplanation.AnnotatedPermissionMatching? = nil

  /// Lists all exception permissions in the deny rule and indicates whether each
  /// permission matches the permission in the request.
  ///
  /// Each key identifies a exception permission in the rule, and each value
  /// indicates whether the exception permission matches the permission in the
  /// request.
  public var exceptionPermissions: [Swift.String: DenyRuleExplanation.AnnotatedPermissionMatching] =
    [:]

  /// Indicates whether the principal is listed as a denied principal in the
  /// deny rule, either directly or through membership in a principal set.
  public var combinedDeniedPrincipal: DenyRuleExplanation.AnnotatedDenyPrincipalMatching? = nil

  /// Lists all denied principals in the deny rule and indicates whether each
  /// principal matches the principal in the request, either directly or through
  /// membership in a principal set.
  ///
  /// Each key identifies a denied principal in the rule, and each value
  /// indicates whether the denied principal matches the principal in the
  /// request.
  public var deniedPrincipals: [Swift.String: DenyRuleExplanation.AnnotatedDenyPrincipalMatching] =
    [:]

  /// Indicates whether the principal is listed as an exception principal in the
  /// deny rule, either directly or through membership in a principal set.
  public var combinedExceptionPrincipal: DenyRuleExplanation.AnnotatedDenyPrincipalMatching? = nil

  /// Lists all exception principals in the deny rule and indicates whether each
  /// principal matches the principal in the request, either directly or through
  /// membership in a principal set.
  ///
  /// Each key identifies a exception principal in the rule, and each value
  /// indicates whether the exception principal matches the principal in the
  /// request.
  public var exceptionPrincipals:
    [Swift.String: DenyRuleExplanation.AnnotatedDenyPrincipalMatching] = [:]

  /// The relevance of this role binding to the overall determination for the
  /// entire policy.
  public var relevance: HeuristicRelevance = HeuristicRelevance()

  /// A condition expression that specifies when the deny rule denies the
  /// principal access.
  ///
  /// To learn about IAM Conditions, see
  /// https://cloud.google.com/iam/help/conditions/overview.
  public var condition: GoogleType.Expr? = nil

  /// Condition evaluation state for this role binding.
  public var conditionExplanation: ConditionExplanation? = nil

  /// Initialize a new instance of `DenyRuleExplanation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DenyRuleExplanation().with { $0.denyAccessState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Details about whether the permission in the request is denied by the
  /// deny rule.
  public struct AnnotatedPermissionMatching: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Indicates whether the permission in the request is denied by the deny
    /// rule.
    public var permissionMatchingState: PermissionPatternMatchingState =
      PermissionPatternMatchingState()

    /// The relevance of the permission status to the overall determination for
    /// the rule.
    public var relevance: HeuristicRelevance = HeuristicRelevance()

    /// Initialize a new instance of `AnnotatedPermissionMatching`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnnotatedPermissionMatching().with { $0.permissionMatchingState = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.DenyRuleExplanation.AnnotatedPermissionMatching"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Details about whether the principal in the request is listed as a denied
  /// principal in the deny rule, either directly or through membership in a
  /// principal set.
  public struct AnnotatedDenyPrincipalMatching: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Indicates whether the principal is listed as a denied principal in the
    /// deny rule, either directly or through membership in a principal set.
    public var membership: MembershipMatchingState = MembershipMatchingState()

    /// The relevance of the principal's status to the overall determination for
    /// the role binding.
    public var relevance: HeuristicRelevance = HeuristicRelevance()

    /// Initialize a new instance of `AnnotatedDenyPrincipalMatching`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnnotatedDenyPrincipalMatching().with { $0.membership = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.DenyRuleExplanation.AnnotatedDenyPrincipalMatching"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.DenyRuleExplanation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
