// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Details about how the relevant IAM deny policies affect the final access
/// state.
public struct DenyPolicyExplanation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Indicates whether the principal is denied the specified permission for
  /// the specified resource, based on evaluating all applicable IAM deny
  /// policies.
  public var denyAccessState: DenyAccessState = DenyAccessState()

  /// List of resources with IAM deny policies that were evaluated to check the
  /// principal's denied permissions, with annotations to indicate how each
  /// policy contributed to the final result.
  ///
  /// The list of resources includes the policy for the resource itself, as well
  /// as policies that are inherited from higher levels of the resource
  /// hierarchy, including the organization, the folder, and the project. The
  /// order of the resources starts from the resource and climbs up the resource
  /// hierarchy.
  ///
  /// To learn more about the resource hierarchy, see
  /// https://cloud.google.com/iam/help/resource-hierarchy.
  public var explainedResources: [ExplainedDenyResource] = []

  /// The relevance of the deny policy result to the overall access state.
  public var relevance: HeuristicRelevance = HeuristicRelevance()

  /// Indicates whether the permission to troubleshoot is supported in deny
  /// policies.
  public var permissionDeniable: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DenyPolicyExplanation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DenyPolicyExplanation().with { $0.denyAccessState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.DenyPolicyExplanation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
