// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleIAMV2

/// Details about how a specific IAM deny policy [Policy][google.iam.v2.Policy]
/// contributed to the access check.
///
/// [google.iam.v2.Policy]: https://www.google.com/search?q=Swift+google.iam.v2+GoogleIAMV2.Policy
public struct ExplainedDenyPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Indicates whether _this policy_ denies the specified permission
  /// to the specified principal for the specified resource.
  ///
  /// This field does _not_ indicate whether the principal actually has the
  /// permission for the resource. There might be another policy that overrides
  /// this policy. To determine whether the principal actually has the
  /// permission, use the `overall_access_state` field in the
  /// [TroubleshootIamPolicyResponse][google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse].
  ///
  /// [google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse]: <doc:TroubleshootIamPolicyResponse>
  public var denyAccessState: DenyAccessState = DenyAccessState()

  /// The IAM deny policy attached to the resource.
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is omitted.
  public var policy: GoogleIAMV2.Policy? = nil

  /// Details about how each rule in the policy affects the principal's inability
  /// to use the permission for the resource. The order of the deny rule matches
  /// the order of the rules in the deny policy.
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is omitted.
  public var ruleExplanations: [DenyRuleExplanation] = []

  /// The relevance of this policy to the overall access state in the
  /// [TroubleshootIamPolicyResponse][google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse].
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is omitted.
  ///
  /// [google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse]: <doc:TroubleshootIamPolicyResponse>
  public var relevance: HeuristicRelevance = HeuristicRelevance()

  /// Initialize a new instance of `ExplainedDenyPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExplainedDenyPolicy().with { $0.denyAccessState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.ExplainedDenyPolicy"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
