// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleIAMV1
@_spi(GoogleCloudInternal) import GoogleWKT

/// Details about how a specific IAM allow policy contributed to the final access
/// state.
public struct ExplainedAllowPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Indicates whether _this policy_ provides the specified permission
  /// to the specified principal for the specified resource.
  ///
  /// This field does _not_ indicate whether the principal actually has the
  /// permission for the resource. There might be another policy that overrides
  /// this policy. To determine whether the principal actually has the
  /// permission, use the `overall_access_state` field in the
  /// [TroubleshootIamPolicyResponse][google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse].
  ///
  /// [google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse]: <doc:TroubleshootIamPolicyResponse>
  public var allowAccessState: AllowAccessState = AllowAccessState()

  /// The full resource name that identifies the resource. For example,
  /// `//compute.googleapis.com/projects/my-project/zones/us-central1-a/instances/my-instance`.
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is omitted.
  ///
  /// For examples of full resource names for Google Cloud services, see
  /// https://cloud.google.com/iam/help/troubleshooter/full-resource-names.
  public var fullResourceName: Swift.String = Swift.String()

  /// Details about how each role binding in the policy affects the principal's
  /// ability, or inability, to use the permission for the resource. The order of
  /// the role bindings matches the role binding order in the policy.
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is omitted.
  public var bindingExplanations: [AllowBindingExplanation] = []

  /// The relevance of this policy to the overall access state in the
  /// [TroubleshootIamPolicyResponse][google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse].
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is omitted.
  ///
  /// [google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse]: <doc:TroubleshootIamPolicyResponse>
  public var relevance: HeuristicRelevance = HeuristicRelevance()

  /// The IAM allow policy attached to the resource.
  ///
  /// If the sender of the request does not have access to the policy, this field
  /// is empty.
  public var policy: GoogleIAMV1.Policy? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExplainedAllowPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExplainedAllowPolicy().with { $0.allowAccessState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let allowAccessState = CodingKeys(stringValue: "allowAccessState")
    static let fullResourceName = CodingKeys(stringValue: "fullResourceName")
    static let bindingExplanations = CodingKeys(stringValue: "bindingExplanations")
    static let relevance = CodingKeys(stringValue: "relevance")
    static let policy = CodingKeys(stringValue: "policy")

    static let _knownKeys: Set<Swift.String> = [
      "allowAccessState",
      "fullResourceName",
      "bindingExplanations",
      "relevance",
      "policy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(AllowAccessState.self, forKey: .allowAccessState) {
      self.allowAccessState = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fullResourceName) {
      self.fullResourceName = value
    }
    if let value = try container.decodeIfPresent(
      [AllowBindingExplanation].self, forKey: .bindingExplanations)
    {
      self.bindingExplanations = value
    }
    if let value = try container.decodeIfPresent(HeuristicRelevance.self, forKey: .relevance) {
      self.relevance = value
    }
    self.policy = try container.decodeIfPresent(GoogleIAMV1.Policy.self, forKey: .policy)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.allowAccessState, forKey: .allowAccessState)
    try container.encode(self.fullResourceName, forKey: .fullResourceName)
    try container.encode(self.bindingExplanations, forKey: .bindingExplanations)
    try container.encode(self.relevance, forKey: .relevance)
    try container.encodeIfPresent(self.policy, forKey: .policy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.ExplainedAllowPolicy"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
