// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// IAM Policy Troubleshooter service.
///
/// This service helps you troubleshoot access issues for Google Cloud resources.
///
/// @Snippet(path: "PolicyTroubleshooterQuickstart")
public final class PolicyTroubleshooterClient: Clients.PolicyTroubleshooterProtocol, Sendable {
  let inner: any Clients.PolicyTroubleshooterStub

  /// Creates a new `PolicyTroubleshooterClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.PolicyTroubleshooterStub = try Clients.PolicyTroubleshooterTransport(
      options)
    inner = Clients.PolicyTroubleshooterRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.PolicyTroubleshooterLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Checks whether a principal has a specific permission for a specific
  /// resource, and explains why the principal does or doesn't have that
  /// permission.
  ///
  /// @Snippet(path: "PolicyTroubleshooter_TroubleshootIamPolicy")
  public func troubleshootIamPolicy(
    request: TroubleshootIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicyTroubleshooterIAMV3.TroubleshootIamPolicyResponse {
    try await self.inner.troubleshootIamPolicy(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `PolicyTroubleshooterClient`.
  ///
  /// To mock `PolicyTroubleshooterClient` change your functions to receive
  /// `some PolicyTroubleshooterProtocol` or `any PolicyTroubleshooterProtocol`
  /// and pass a mock implementation in your tests.
  public protocol PolicyTroubleshooterProtocol {
    /// See `PolicyTroubleshooterClient.troubleshootIamPolicy`.
    func troubleshootIamPolicy(request: TroubleshootIamPolicyRequest) async throws
      -> GoogleCloudPolicyTroubleshooterIAMV3.TroubleshootIamPolicyResponse

    /// See `PolicyTroubleshooterClient.troubleshootIamPolicy`.
    func troubleshootIamPolicy(
      request: TroubleshootIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicyTroubleshooterIAMV3.TroubleshootIamPolicyResponse
  }
}

// Default implementations
extension Clients.PolicyTroubleshooterProtocol {
  public func troubleshootIamPolicy(request: TroubleshootIamPolicyRequest) async throws
    -> GoogleCloudPolicyTroubleshooterIAMV3.TroubleshootIamPolicyResponse
  {
    try await self.troubleshootIamPolicy(request: request, options: .init())
  }

  public func troubleshootIamPolicy(
    request: TroubleshootIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicyTroubleshooterIAMV3.TroubleshootIamPolicyResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
