// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Whether a role includes a specific permission.
public enum RolePermissionInclusionState: Codable, Equatable, Sendable {
  /// Not specified.
  case unspecified
  /// The permission is included in the role.
  case rolePermissionIncluded
  /// The permission is not included in the role.
  case rolePermissionNotIncluded
  /// The sender of the request is not allowed to access the role definition.
  case rolePermissionUnknownInfo
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .rolePermissionIncluded: return 1
    case .rolePermissionNotIncluded: return 2
    case .rolePermissionUnknownInfo: return 3
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "ROLE_PERMISSION_INCLUSION_STATE_UNSPECIFIED"
    case .rolePermissionIncluded: return "ROLE_PERMISSION_INCLUDED"
    case .rolePermissionNotIncluded: return "ROLE_PERMISSION_NOT_INCLUDED"
    case .rolePermissionUnknownInfo: return "ROLE_PERMISSION_UNKNOWN_INFO"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RolePermissionInclusionState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "ROLE_PERMISSION_INCLUSION_STATE_UNSPECIFIED": self = .unspecified
    case "ROLE_PERMISSION_INCLUDED": self = .rolePermissionIncluded
    case "ROLE_PERMISSION_NOT_INCLUDED": self = .rolePermissionNotIncluded
    case "ROLE_PERMISSION_UNKNOWN_INFO": self = .rolePermissionUnknownInfo
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RolePermissionInclusionState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .rolePermissionIncluded
    case 2: self = .rolePermissionNotIncluded
    case 3: self = .rolePermissionUnknownInfo
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .rolePermissionIncluded: return try container.encode(1)
    case .rolePermissionNotIncluded: return try container.encode(2)
    case .rolePermissionUnknownInfo: return try container.encode(3)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
