// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Response for
/// [TroubleshootIamPolicy][google.cloud.policytroubleshooter.iam.v3.PolicyTroubleshooter.TroubleshootIamPolicy].
///
/// [google.cloud.policytroubleshooter.iam.v3.PolicyTroubleshooter.TroubleshootIamPolicy]: <doc:PolicyTroubleshooterClient/troubleshootIamPolicy(request:options:)>
public struct TroubleshootIamPolicyResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Indicates whether the principal has the specified permission for the
  /// specified resource, based on evaluating all types of the applicable IAM
  /// policies.
  public var overallAccessState: TroubleshootIamPolicyResponse.OverallAccessState =
    TroubleshootIamPolicyResponse.OverallAccessState()

  /// The access tuple from the request, including any provided context used to
  /// evaluate the condition.
  public var accessTuple: AccessTuple? = nil

  /// An explanation of how the applicable IAM allow policies affect the final
  /// access state.
  public var allowPolicyExplanation: AllowPolicyExplanation? = nil

  /// An explanation of how the applicable IAM deny policies affect the final
  /// access state.
  public var denyPolicyExplanation: DenyPolicyExplanation? = nil

  /// Initialize a new instance of `TroubleshootIamPolicyResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TroubleshootIamPolicyResponse().with { $0.overallAccessState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Whether the principal has the permission on the resource.
  public enum OverallAccessState: Codable, Equatable, Sendable {
    /// Not specified.
    case unspecified
    /// The principal has the permission.
    case canAccess
    /// The principal doesn't have the permission.
    case cannotAccess
    /// The principal might have the permission, but the sender can't access all
    /// of the information needed to fully evaluate the principal's access.
    case unknownInfo
    /// The principal might have the permission, but Policy Troubleshooter can't
    /// fully evaluate the principal's access because the sender didn't provide
    /// the required context to evaluate the condition.
    case unknownConditional
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .canAccess: return 1
      case .cannotAccess: return 2
      case .unknownInfo: return 3
      case .unknownConditional: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OVERALL_ACCESS_STATE_UNSPECIFIED"
      case .canAccess: return "CAN_ACCESS"
      case .cannotAccess: return "CANNOT_ACCESS"
      case .unknownInfo: return "UNKNOWN_INFO"
      case .unknownConditional: return "UNKNOWN_CONDITIONAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OverallAccessState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OVERALL_ACCESS_STATE_UNSPECIFIED": self = .unspecified
      case "CAN_ACCESS": self = .canAccess
      case "CANNOT_ACCESS": self = .cannotAccess
      case "UNKNOWN_INFO": self = .unknownInfo
      case "UNKNOWN_CONDITIONAL": self = .unknownConditional
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OverallAccessState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .canAccess
      case 2: self = .cannotAccess
      case 3: self = .unknownInfo
      case 4: self = .unknownConditional
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .canAccess: return try container.encode(1)
      case .cannotAccess: return try container.encode(2)
      case .unknownInfo: return try container.encode(3)
      case .unknownConditional: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.policytroubleshooter.iam.v3.TroubleshootIamPolicyResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
